config/routes.rb
Rails.application.routes.draw do
  get 'pockets/index'
  get 'pockets/new'
  get 'pockets/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :pockets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

        def index       
            @exam = Exam.all
          end
      
          def show        
            id = params[:id]  
            @exam = Exam.find(id)       
          end 
      
          def new
            @exam = Exam.new
          end
          
          def create  
            exam = Exam.new(exam_params)
            exam.save
            flash[:notice] = 'exam has been created'
            redirect_to exams_path
          end
          
          def edit    
            id = params[:id]  
            @exam = Exam.find(id)
          end
          
          def update      
            @exam = Exam.find(params[:id])
            @exam.update(exam_params)
            flash[:notice] = 'exam has been updated'
            redirect_to exam_path(@exam)
          end
          
          def destroy     
            @exam = Exam.find(params[:id])
            @exam.destroy
            flash[:notice] = 'exam has been deleted'
            redirect_to exams_path
          end
              
          private 
          def exam_params
              params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :label, :student_id)
          end
    
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
    def index       
      @pocket = Pocket.all
    end

    def show        
      id = params[:id]  
      @pocket = Pocket.find(id)       
    end 

    def new
      @pocket = Pocket.new
    end
    
    def create  
      pocket = Pocket.new(pocket_params)
      pocket.save
      flash[:notice] = 'pocket has been created'
      redirect_to pockets_path
    end
    
    def edit    
      id = params[:id]  
      @pocket = Pocket.find(id)
    end
    
    def update      
      @pocket = Pocket.find(params[:id])
      @pocket.update(pocket_params)
      flash[:notice] = 'pocket has been updated'
      redirect_to pocket_path(@pocket)
    end
    
    def destroy     
      @pocket = Pocket.find(params[:id])
      @pocket.destroy
      flash[:notice] = 'pocket has been deleted'
      redirect_to pockets_path
    end
        
    private 
    def pocket_params
        params.require(:pocket).permit(:balance, :student_id, :teacher_id)
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController


    def index       
        @report = Report.all
      end
  
    def show        
        id = params[:id]  
        @report = Report.find(id)       
    end 

    def new
        @report = Report.new
    end

    def create
        @report = Report.new(params[:id])
        if @report.save
          flash[:success] = "Report successfully created"
        end
          redirect_to reports_path
    end
    
    def edit    
        id = params[:id]  
        @report = Report.find(id)
      end
      
      def update      
        @report = Report.find(params[:id])
        @report.update(report_params)
        flash[:notice] = 'report has been updated'
        redirect_to report_path(@report)
      end
      
      def destroy     
        @report = Report.find(params[:id])
        @report.destroy
        flash[:notice] = 'report has been deleted'
        redirect_to reports_path
      end
          
      private 
      def report_params
          params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
      end
  
    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index       
        @student = Student.all
      end
  
      def show        
        id = params[:id]  
        @student = Student.find(id)       
      end 
  
      def new
        @student = Student.new
      end
      
      def create  
        student = Student.new(student_params)
        student.save
        flash[:notice] = 'student has been created'
        redirect_to students_path
      end
      
      def edit    
        id = params[:id]  
        @student = Student.find(id)
      end
      
      def update      
        @student = Student.find(params[:id])
        @student.update(student_params)
        flash[:notice] = 'student has been updated'
        redirect_to student_path(@student)
      end
      
      def destroy     
        @student = Student.find(params[:id])
        @student.destroy
        flash[:notice] = 'student has been deleted'
        redirect_to students_path
      end
          
      private 
      def student_params
          params.require(:student).permit(:name, :username, :age, :kelas, :address, :city, :nik)
      end
  

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

    def index       
        @teacher = Teacher.all
      end
  
      def show        
        id = params[:id]  
        @teacher = Teacher.find(id)       
      end 
  
      def new
        @teacher = Teacher.new
      end
      
      def create  
        teacher = Teacher.new(teacher_params)
        teacher.save
        flash[:notice] = 'teacher has been created'
        redirect_to teachers_path
      end
      
      def edit    
        id = params[:id]  
        @teacher = Teacher.find(id)
      end
      
      def update      
        @teacher = Teacher.find(params[:id])
        @teacher.update(teacher_params)
        flash[:notice] = 'teacher has been updated'
        redirect_to teacher_path(@teacher)
      end
      
      def destroy     
        @teacher = Teacher.find(params[:id])
        @teacher.destroy
        flash[:notice] = 'teacher has been deleted'
        redirect_to teachers_path
      end
  
      private 
      def teacher_params
          params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
      end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<meta charset="UTF-8">
	<title>CRUD</title>
</head>
<body>
<div class="container-fluid">
<br><div class="pull-right">
<%= link_to 'Back', exams_path, class: 'btn btn-danger' %>
</div>    
</div>
<div class="container mt-5">
<div class="card">
	<div class="card-body">
    <h2>Edit exam</h2> <hr>
        <%= form_for @exam , {class: "form-horizontal"} do |f| %>
    
            <%= f.label :title, "title : ", class: "control-label" %>
                <%= f.text_field :title, class: "form-control" %> <br>

            <%= f.label :mapel, "mapel:  ", class: "control-label" %>
                <%= f.text_field :mapel, class: "form-control" %><br>

            <%= f.label :duration, "duration : ", class: "control-label" %>
                <%= f.text_field :duration, class: "form-control" %> <br> 

            
            <%= f.label :nilai, "nilai: ", class: "control-label" %>
                <%= f.text_field :nilai, class: "form-control" %><br>

            <%= f.label :status, "status : ", class: "control-label" %>
                <%= f.text_field :status, class: "form-control" %><br>

            <%= f.label :label, "label: ", class: "control-label" %>
                <%= f.text_field :label, class: "form-control" %><br>

            <%= f.label :student_id, "student_id: ", class: "control-label" %>
                <%= f.text_field :student_id, class: "form-control" %><br>

            <%= f.submit 'Simpan', class: 'btn btn-primary'%>

        <% end %>
        </div>
    </div>
</div>
</body>
</html>
 
 

app/views/exams/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <title>index</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    <% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %>
      
<div class="container-fluid">
 <%= render './nav' %>
    <br> <br>
      <h1>Exam</h1> 
    <br>
<table class="table">
    <thead>
        <tr>
            <th>title</th>
            <th>mapel</th>
            <th>duration</th>
            <th>nilai</th>
            <th>status</th>
            <th>label</th>
            <th>student_id</th>
            <th>Action</th>
        </tr>
    </thead>
    <% @exam.each do |b| %>
    <tbody>
        <tr>
            <td><%= b.title %></td>
            <td><%= b.mapel %></td>
            <td><%= b.duration %></td>
            <td><%= b.nilai %></td>
            <td><%= b.status %></td>
            <td><%= b.label %></td>
            <td><%= b.student_id %></td>
            <td><%= link_to 'Detail ', exam_path(b), class: 'btn btn-ghost' %>  <%= link_to ' Edit', edit_exam_path(b), class: 'btn btn-warning' %>  <%= link_to 'Delete', exam_path(b), class: 'btn btn-danger' , method: :delete, data: {confirm: "Are You sure??"} %></td>
       </tr>
    </tbody>
    <% end %>
</table>
<br>
<div class="pull-right">
<%= link_to 'New exam', new_exam_path, class: 'btn btn-primary'%>
</div>
    
</div>
    </body>
</html>     

app/views/exams/new.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<meta charset="UTF-8">
	<title>CRUD</title>
</head>
<body>
<div class="container-fluid">
<br><div class="pull-right">
<%= link_to 'Back', exams_path, class: 'btn btn-danger' %>
</div>    
</div>
<div class="container mt-5">
<div class="card">
	<div class="card-body">
    <h2>Input exam</h2> <hr>
        <%= form_for @exam , {class: "form-horizontal"} do |f| %>
    
            <%= f.label :title, "title : ", class: "control-label" %>
                <%= f.text_field :title, class: "form-control" %> <br>

            <%= f.label :mapel, "mapel:  ", class: "control-label" %>
                <%= f.text_field :mapel, class: "form-control" %><br>

            <%= f.label :duration, "duration : ", class: "control-label" %>
                <%= f.text_field :duration, class: "form-control" %> <br> 

            
            <%= f.label :nilai, "nilai: ", class: "control-label" %>
                <%= f.text_field :nilai, class: "form-control" %><br>

            <%= f.label :status, "status : ", class: "control-label" %>
                <%= f.text_field :status, class: "form-control" %><br>

            <%= f.label :label, "label: ", class: "control-label" %>
                <%= f.text_field :label, class: "form-control" %><br>

            <%= f.label :student_id, "student_id: ", class: "control-label" %>
                <%= f.text_field :student_id, class: "form-control" %><br>

            <%= f.submit 'Simpan', class: 'btn btn-primary'%>

        <% end %>
        </div>
    </div>
</div>
</body>
</html>
 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kejarid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pockets/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <title>index</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    <% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> 
<div class="container-fluid">
 <%= render './nav' %>
    <br><br>
        <h1>Pocket</h1>
        <br>
<table class="table">
    <thead>
        <tr>
            <th>balance</th>
            <th>student_id</th>
            <th>teacher_id</th>
            <th>Action</th>
        </tr>
    </thead>
    <% @pocket.each do |b| %>
    <tbody>
        <tr>
            <td><%= b.balance %></td>
            <td><%= b.student_id %></td>
            <td><%= b.teacher_id %></td>
            <td><%= link_to 'Detail ', pocket_path(b), class: 'btn btn-ghost' %>  <%= link_to ' Edit', edit_pocket_path(b), class: 'btn btn-warning' %>  <%= link_to 'Delete', pockets_path(b), class: 'btn btn-danger' , method: :delete, data: {confirm: "Are You sure??"} %></td>
       </tr>
    </tbody>
    <% end %>
</table>
<br>
<div class="pull-right">
<%= link_to 'New pocket', new_pocket_path, class: 'btn btn-primary'%>
</div>
    
</div>
    </body>
</html>     

app/views/reports/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <title>index</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    <% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %>
    
<div class="container-fluid">
 <%= render './nav' %>
    <br><br>
        <h1>Report</h1> 
    <br>
<table class="table">
    <thead>
        <tr>
            <th>title</th>
            <th>hasil</th>
            <th>mapel</th>
            <th>teacher_id</th>
            <th>student_id</th>
            <th>date</th>
            <th>action</th>
        </tr>
    </thead>
    <% @report.each do |b| %>
    <tbody>
        <tr>
            <td><%= b.title %></td>
            <td><%= b.hasil %></td>
            <td><%= b.mapel %></td>
            <td><%= b.teacher_id %></td>
            <td><%= b.student_id %></td>
            <td><%= b.date %></td>
            <td><%= link_to 'Detail ', report_path(b), class: 'btn btn-ghost' %>  <%= link_to ' Edit', edit_report_path(b), class: 'btn btn-warning' %>  <%= link_to 'Delete', report_path(b), class: 'btn btn-danger' , method: :delete, data: {confirm: "Are You sure??"} %></td>
       </tr>
    </tbody>
    <% end %>
</table>
<br>
<div class="pull-right">
<%= link_to 'New Report', new_report_path, class: 'btn btn-primary'%>
</div>
    
</div>
    </body>
</html>     

app/views/students/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <title>index</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    <% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %>
        
<div class="container-fluid">
 <%= render './nav' %>
    <br><br>
    <h1>Students</h1>
     <br>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Username</th>
            <th>age</th>
            <th>kelas</th>
            <th>address</th>
            <th>city</th>
            <th>NIK</th>
            <th>action</th>
        </tr>
    </thead>
    <% @student.each do |b| %>
    <tbody>
        <tr>
            <td><%= b.name %></td>
            <td><%= b.username %></td>
            <td><%= b.age %></td>
            <td><%= b.kelas %></td>
            <td><%= b.address %></td>
            <td><%= b.city %></td>
            <td><%= b.nik %></td>
            <td><%= link_to 'Detail ', student_path(b),class: "btn btn-ghost" %> | <%= link_to ' Edit', edit_student_path(b),class: "btn btn-warning" %> | <%= link_to 'Delete', student_path(b),class: "btn btn-danger" , method: :delete, data: {confirm: "Are You sure??"} %></td>
       </tr>
    </tbody>
    <% end %>
</table>
<br>
<div class="pull-right">
<%= link_to 'New student', new_student_path, class: 'btn btn-primary' %>
</div>
    
</div>
    </body>
</html>     

app/views/teachers/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <title>index</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    <% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %>
    
<div class="container-fluid">
        <%= render './nav' %>
    <br><br>
        <h1>Teacher</h1>
        <br>
<table class="table">
    <thead>
        <tr>
            <th>NIK</th>
            <th>Name</th>
            <th>age</th>
            <th>kelas</th>
            <th>Mapel</th>
            <th>action</th>
        </tr>
    </thead>
    <% @teacher.each do |b| %>
    <tbody>
        <tr>
            <td><%= b.nik %></td>
            <td><%= b.name %></td>
            <td><%= b.age %></td>
            <td><%= b.kelas %></td>
            <td><%= b.mapel %></td>
            <td><%= link_to 'Detail ', teacher_path(b),class: "btn btn-ghost" %> | <%= link_to ' Edit', edit_teacher_path(b),class: "btn btn-warning" %> | <%= link_to 'Delete', teacher_path(b),class: "btn btn-danger" , method: :delete, data: {confirm: "Are You sure??"} %></td>
       </tr>
    </tbody>
    <% end %>
</table>
<br>
<div class="pull-right">
<%= link_to 'New teacher', new_teacher_path, class: 'btn btn-primary'%>
</div>
    
</div>
    </body>
</html>     